// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8JeuvnINZSnZemmNYfjCV9usSbAIHgpg',
    appId: '1:845715742054:web:73b3f1df256f7803cdfca7',
    messagingSenderId: '845715742054',
    projectId: 'laundary-15e76',
    authDomain: 'laundary-15e76.firebaseapp.com',
    databaseURL: 'https://laundary-15e76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laundary-15e76.firebasestorage.app',
    measurementId: 'G-1RQ5KWLX53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc78LVSEYODcZU5LaR3w2uwPDllvvLvuQ',
    appId: '1:845715742054:android:4251e18c71bdb082cdfca7',
    messagingSenderId: '845715742054',
    projectId: 'laundary-15e76',
    databaseURL: 'https://laundary-15e76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laundary-15e76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc78LVSEYODcZU5LaR3w2uwPDllvvLvuQ',
    appId: '1:845715742054:ios:REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: '845715742054',
    projectId: 'laundary-15e76',
    storageBucket: 'laundary-15e76.firebasestorage.app',
    iosBundleId: 'com.laundary',
  );
}
